In [1]:
%matplotlib qt
import numpy as np
import py4DSTEM
import os
import matplotlib.pyplot as plt
import pymatgen
import math
from scipy.spatial.transform import Rotation as R
from mpl_toolkits.mplot3d import Axes3D

# Load crystal File Corundum

In [2]:
cif = 'Q:\Data\_CIF-Files\ZnO.cif'

#Define crystal Corundum
crystal_corundum = py4DSTEM.process.diffraction.Crystal.from_CIF(cif,conventional_standard_structure=True,)

k_max_Corundum = 2.1
q_SF_Corundum, I_SF_Corundum = crystal_corundum.calculate_structure_factors(k_max_Corundum, return_intensities=True)

crystal_corundum.plot_structure_factors(zone_axis_lattice=[0,0,1],)


D:\Anaconda\lib\site-packages\pymatgen\io\cif.py:1155: UserWarning: Issues encountered while parsing CIF: Some fractional coordinates rounded to ideal values to avoid issues with finite precision.
  warnings.warn("Issues encountered while parsing CIF: " + "\n".join(self.warnings))


### Define Reciprocal points of corundum

In [3]:
points_Corundum = [crystal_corundum.g_vec_all]

print(points_Corundum)

[array([[-1.85336714, -1.85336714, -1.85336714, ...,  1.85336714,
         1.85336714,  1.85336714],
       [-0.71336134, -0.71336134, -0.71336134, ...,  0.71336134,
         0.71336134,  0.71336134],
       [-0.57448579, -0.38299053, -0.19149526, ...,  0.19149526,
         0.38299053,  0.57448579]])]


In [4]:
points_Corundum_new = [arr[:, i] for arr in points_Corundum for i in range(arr.shape[1])]

print(points_Corundum_new)

[array([-1.85336714, -0.71336134, -0.57448579]), array([-1.85336714, -0.71336134, -0.38299053]), array([-1.85336714, -0.71336134, -0.19149526]), array([-1.85336714e+00, -7.13361345e-01,  1.89143345e-16]), array([-1.85336714, -0.71336134,  0.19149526]), array([-1.85336714, -0.71336134,  0.38299053]), array([-1.85336714, -0.71336134,  0.57448579]), array([-1.85336714, -0.35668067, -0.76598105]), array([-1.85336714, -0.35668067, -0.57448579]), array([-1.85336714, -0.35668067, -0.38299053]), array([-1.85336714, -0.35668067, -0.19149526]), array([-1.85336714e+00, -3.56680672e-01,  1.51314676e-16]), array([-1.85336714, -0.35668067,  0.19149526]), array([-1.85336714, -0.35668067,  0.38299053]), array([-1.85336714, -0.35668067,  0.57448579]), array([-1.85336714, -0.35668067,  0.76598105]), array([-1.85336714e+00,  6.66133815e-16, -7.65981050e-01]), array([-1.85336714e+00,  6.66133815e-16, -3.82990525e-01]), array([-1.85336714e+00,  6.66133815e-16,  1.13486007e-16]), array([-1.85336714e+00,  6.

In [5]:
# Rotate 45° around z 
angle_degrees = 75
angle_radians = np.radians(angle_degrees)

def rotate_3d_array(array, angle):
    rotation_matrix = np.array([
        [np.cos(angle), -np.sin(angle), 0],
        [np.sin(angle), np.cos(angle), 0],
        [0, 0, 1]
    ])
    return np.dot(array, rotation_matrix)

# Rotate each array in the list by the given angle
points_Corundum_new_rotated = [rotate_3d_array(arr, angle_radians) for arr in points_Corundum_new]


###### Plot Reciprocal points Corundum

In [6]:
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.scatter([p[0] for p in points_Corundum], [p[1] for p in points_Corundum], [p[2] for p in points_Corundum])
ax.set_xlabel('b1')
ax.set_ylabel('b2')
ax.set_zlabel('b3')
plt.show()

In [48]:
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.scatter([p[0] for p in points_Corundum_new_rotated], [p[1] for p in points_Corundum_new_rotated], [p[2] for p in points_Corundum_new_rotated])
ax.set_xlabel('b1')
ax.set_ylabel('b2')
ax.set_zlabel('b3')
plt.show()

# Define Au Lattice

In [7]:
# Define Gold structure
pos = np.array([
    [0.0, 0.0, 0.0],
    [0.0, 0.5, 0.5],
    [0.5, 0.0, 0.5],
    [0.5, 0.5, 0.0],
])
atom_num = 79
a = 4.08
cell = a

crystal_Au = py4DSTEM.process.diffraction.Crystal(pos,atom_num,cell)

# Calculate and plot Au structure factors
h = 2
k = 2
l = 2

k_max_Au = (((h**2+k**2+l**2)**0.5)/a) + 0.001 
q_SF_Au, I_SF_Au = crystal_Au.calculate_structure_factors(k_max_Au, return_intensities=True)

crystal_Au.plot_structure_factors(zone_axis_lattice=[1,1,0],)

In [8]:
crystal_Au.plot_structure(
    zone_axis_lattice=[1,1,0],
    figsize=(4,4),
)

### Generate and plot diffraction patterns

In [9]:
# specify the accelerating voltage
crystal_Au.setup_diffraction(300e3)

In [10]:
zone_axis_test = [1,1,1]  # Zone axis
# zone_axis_test = [0,0,1]  # Zone axis
# x_proj_test = [1,0,0]  # in-plane projection vector

bragg_peaks = crystal_Au.generate_diffraction_pattern(
    zone_axis_lattice = zone_axis_test,
    # proj_x_lattice = x_proj_test,
    sigma_excitation_error=0.02
)

py4DSTEM.process.diffraction.plot_diffraction_pattern(
    bragg_peaks,
    # add_labels=False,
    figsize=(8,8),
    # shift_labels=0.2,
)

In [87]:
#cif = 'Q:\Data\_CIF-Files\Gold.cif'

#Define crystal Corundum
#crystal_Au = py4DSTEM.process.diffraction.Crystal.from_CIF(cif,conventional_standard_structure=True,)

#k_max_Au = 0.9
#q_SF_Au, I_SF_Au = crystal_Au.calculate_structure_factors(k_max_Au, return_intensities=True)

#crystal_Au.plot_structure_factors(zone_axis_lattice=[0,0,1],)

### Define Reciprocal points of Au

In [11]:
points_Au = [crystal_Au.g_vec_all]

print(points_Au)

[array([[-7.35294118e-01, -7.35294118e-01, -7.35294118e-01,
        -7.35294118e-01, -4.90196078e-01, -4.90196078e-01,
        -4.90196078e-01, -4.90196078e-01, -4.90196078e-01,
        -4.90196078e-01, -4.90196078e-01, -4.90196078e-01,
        -4.90196078e-01, -2.45098039e-01, -2.45098039e-01,
        -2.45098039e-01, -2.45098039e-01, -2.45098039e-01,
        -2.45098039e-01, -2.45098039e-01, -2.45098039e-01,
        -2.45098039e-01, -2.45098039e-01, -2.45098039e-01,
        -2.45098039e-01, -3.66118261e-34,  1.83794091e-33,
         4.04200008e-33, -2.20405917e-33,  0.00000000e+00,
         2.20405917e-33, -4.04200008e-33, -1.83794091e-33,
         3.66118261e-34,  2.45098039e-01,  2.45098039e-01,
         2.45098039e-01,  2.45098039e-01,  2.45098039e-01,
         2.45098039e-01,  2.45098039e-01,  2.45098039e-01,
         2.45098039e-01,  2.45098039e-01,  2.45098039e-01,
         2.45098039e-01,  4.90196078e-01,  4.90196078e-01,
         4.90196078e-01,  4.90196078e-01,  4.90196078e-

In [12]:
points_Au_new = [arr[:, i] for arr in points_Au for i in range(arr.shape[1])]

print(points_Au_new)

[array([-0.73529412, -0.24509804, -0.24509804]), array([-0.73529412, -0.24509804,  0.24509804]), array([-0.73529412,  0.24509804, -0.24509804]), array([-0.73529412,  0.24509804,  0.24509804]), array([-0.49019608, -0.49019608, -0.49019608]), array([-4.90196078e-01, -4.90196078e-01,  6.00317058e-17]), array([-0.49019608, -0.49019608,  0.49019608]), array([-4.90196078e-01,  3.00158529e-17, -4.90196078e-01]), array([-4.90196078e-01,  3.00158529e-17,  3.00158529e-17]), array([-4.90196078e-01,  3.00158529e-17,  4.90196078e-01]), array([-0.49019608,  0.49019608, -0.49019608]), array([-0.49019608,  0.49019608,  0.        ]), array([-0.49019608,  0.49019608,  0.49019608]), array([-0.24509804, -0.73529412, -0.24509804]), array([-0.24509804, -0.73529412,  0.24509804]), array([-0.24509804, -0.24509804, -0.73529412]), array([-0.24509804, -0.24509804, -0.24509804]), array([-0.24509804, -0.24509804,  0.24509804]), array([-0.24509804, -0.24509804,  0.73529412]), array([-0.24509804,  0.24509804, -0.735

###### Plot Reciprocal points of Au

In [13]:
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.scatter([p[0] for p in points_Au_new], [p[1] for p in points_Au_new], [p[2] for p in points_Au_new])
ax.set_xlabel('x')
ax.set_ylabel('y')
ax.set_zlabel('z')
plt.show()

#### Rotate Au  lattice in 111 Zone-Axis

In [14]:
# Rotate 45° around z 
angle_degrees = 45
angle_radians = np.radians(angle_degrees)

def rotate_3d_array(array, angle):
    rotation_matrix = np.array([
        [np.cos(angle), -np.sin(angle), 0],
        [np.sin(angle), np.cos(angle), 0],
        [0, 0, 1]
    ])
    return np.dot(array, rotation_matrix)

# Rotate each array in the list by the given angle
points_Au_new_rotated = [rotate_3d_array(arr, angle_radians) for arr in points_Au_new]

# Now, rotated_list will contain the rotated arrays

In [17]:
#Plot rotated lattice

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.scatter([p[0] for p in points_Au_new_rotated], [p[1] for p in points_Au_new_rotated], [p[2] for p in points_Au_new_rotated])
ax.set_xlabel('x')
ax.set_ylabel('y')
ax.set_zlabel('z')
plt.show()

In [15]:
euler_angles_deg = [54.7356, 0, 45]
euler_angles_rad = np.radians(euler_angles_deg)

# Create a Rotation object with the Euler angles
rotation = R.from_euler('xyz', euler_angles_deg, degrees=True)

# Step 3: Apply the rotation to the lattice vectors to get the new (111) orientation
points_Au_new_111 = rotation.apply(points_Au_new_rotated)

In [16]:
print(points_Au_new_111)

[[-7.73210934e-01 -2.07181223e-01  1.41507347e-01]
 [-4.90196132e-01 -4.90196024e-01  4.24522257e-01]
 [-6.69620350e-01  1.79424272e-01  4.24522149e-01]
 [-3.86605548e-01 -1.03590530e-01  7.07537059e-01]
 [-7.73210880e-01 -2.07181277e-01 -2.83014910e-01]
 [-4.90196078e-01 -4.90196078e-01  6.17075130e-17]
 [-2.07181277e-01 -7.73210880e-01  2.83014910e-01]
 [-6.69620296e-01  1.79424218e-01 -1.08107690e-07]
 [-3.86605494e-01 -1.03590584e-01  2.83014802e-01]
 [-1.03590692e-01 -3.86605386e-01  5.66029712e-01]
 [-5.66029712e-01  5.66029712e-01  2.83014694e-01]
 [-2.83014910e-01  2.83014910e-01  5.66029604e-01]
 [-1.08107690e-07  1.08107690e-07  8.49044514e-01]
 [-4.90196024e-01 -4.90196132e-01 -4.24522257e-01]
 [-2.07181223e-01 -7.73210934e-01 -1.41507347e-01]
 [-6.69620242e-01  1.79424163e-01 -4.24522365e-01]
 [-3.86605440e-01 -1.03590638e-01 -1.41507455e-01]
 [-1.03590638e-01 -3.86605440e-01  1.41507455e-01]
 [ 1.79424163e-01 -6.69620242e-01  4.24522365e-01]
 [-5.66029658e-01  5.66029658e-

In [17]:
#Plot rotated lattice

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.scatter([p[0] for p in points_Au_new_111], [p[1] for p in points_Au_new_111], [p[2] for p in points_Au_new_111])
ax.set_xlabel('x')
ax.set_ylabel('y')
ax.set_zlabel('z')
plt.show()

# Do Lattice Rotation

In [22]:
radius = 0.25*(1/a)

overlap = []

for angle in range(361):
    
    # initialize overlap value for this angle
    overlap.append(0)
    
    points_temp = []
    
    for p in points_Au_new_111:
        # convert to polar
        r = (p[0]**2 + p[1]**2)**0.5
        theta = math.atan2(p[1], p[0])
        #rotate
        theta += math.radians(angle)
        # convert to cartesian
        x = r * math.cos(theta)
        y = r * math.sin(theta)
        z = p[2]
        
        # save back into temp pointslist
        points_temp.append([x,y,z])
        
        # go through all points in other system and calculate overlap
        for p1 in points_Corundum_new_rotated:
            x1 = p1[0]
            y1 = p1[1]
            z1 = p1[2]
            d = ( (x1-x)**2 + (y1-y)**2 + (z1-z)**2 )**0.5
            if d < 2*radius:
                factor = (((x**2+y**2+z**2)**0.5)*(x1**2+y1**2+z1**2)**0.5)**2
                if factor == 0:
                    factor = 1
                overlap[angle] += ((1/12)*math.pi*(4*radius + d)*(2*radius - d)**2)*(1/factor) 
                
    if angle == 2:
        fig2 = plt.figure()
        ax = fig2.add_subplot(111, projection='3d')
        ax.scatter([p[0] for p in points_Corundum_new_rotated], [p[1] for p in points_Corundum_new_rotated], [p[2] for p in points_Corundum_new_rotated])
        ax.scatter([p[0] for p in points_temp], [p[1] for p in points_temp], [p[2] for p in points_temp])
        ax.set_xlabel('b1')
        ax.set_ylabel('b2')
        ax.set_zlabel('b3')
        plt.show()

In [23]:
plt.plot(overlap, linestyle="-",marker="x")
plt.xlabel("theta")
plt.ylabel("V / 1/A³")
plt.show()

### Make 2 Column File and save it

In [20]:
x = np.arange(0, 361, 1)
x = list(x)
plt.xlabel("theta")
plt.ylabel("V / A³")
plt.plot(x,overlap,linestyle="-",marker="x" )

In [21]:
filename = "Au_on_ZnO_OR1_begin.txt"
data = np.column_stack((list(x), overlap))


np.savetxt(filename, data, fmt='%.8f', delimiter='\t', header='x\ty', comments='')
#print(f"Data saved to '{filename}' successfully.")